TYPE = ["product", "book"]

CATEGORIES = [
	"3D Printing Filament",
	"3D Printing Supplies",
	"3D Wall Panels",
	"Accessories",
	"Accessories & Parts",
	"Accessories, Hardware & Tools",
	"Account Books",
	"Account Books & Journals",
	"Action Figures",
	"Active",
	"Adapters",
	"Additive Manufacturing Products",
	"Adhesive Vinyl",
	"Adults' Paint-By-Number Kits",
	"Air Compressors & Inflators",
	"Air Conditioner Parts & Accessories",
	"Air Conditioning",
	"Air Fresheners",
	"Air Intake",
	"Air Purifiers",
	"Air Tool Parts & Accessories",
	"Air-Compressor Accessories",
	"All Sony Pictures Titles",
	"All Titles",
	"Alternative Medicine",
	"Americas",
	"Animals",
	"Anklets",
	"Anti-Theft",
	"Antiques & Collectibles",
	"Apparel & Accessories",
	"Appliances",
	"Aprons",
	"Aquarium Décor",
	"Aquarium Pumps & Filters",
	"Area Rugs",
	"Aromatherapy",
	"Arts & Crafts",
	"Arts & Literature",
	"Arts & Photography",
	"Arts, Crafts & Sewing",
	"Athletic Socks",
	"Attachments",
	"Attachments & Brushes",
	"Audio & Video Accessories",
	"Automobile Accessories",
	"Automotive",
	"Baby",
	"Baby & Toddler Toys",
	"Baby Care",
	"Baby Floats",
	"Baby Girls",
	"Baby Products",
	"Back Covers",
	"Back Massagers",
	"Backgrounds",
	"Backpacks",
	"Backyard Birding & Wildlife",
	"Badge Holders",
	"Badge Lanyards",
	"Bags & Cases",
	"Bags, Cases & Sleeves",
	"Bakers",
	"Bakers & Casseroles",
	"Bakeware",
	"Baking & Cookie Sheets",
	"Baking Tools & Accessories",
	"Balloons",
	"Ballpoint Pens",
	"Balls",
	"Bandanas",
	"Banners",
	"Bar & Wine Tools",
	"Bar Tools & Drinkware",
	"Barbells",
	"Barstools",
	"Baseball",
	"Baseball Caps",
	"Basic Bowls",
	"Basic Cases",
	"Basic Collars",
	"Basic Leashes",
	"Basketball",
	"Basketballs",
	"Baskets, Bins & Containers",
	"Bath",
	"Bath & Bathing Accessories",
	"Bath & Body Brushes",
	"Bath Pillows",
	"Bath Sponges",
	"Bath Toys",
	"Bathing Accessories",
	"Bathroom Accessories",
	"Bathroom Fixtures",
	"Bathroom Hardware",
	"Bathroom Safety, Aids & Accessories",
	"Bathroom Sink Faucets & Parts",
	"Bathtub & Shower Trim Systems",
	"Bathtub Faucets & Showerheads",
	"Battery Chargers",
	"Beading & Jewelry Making",
	"Beads & Bead Assortments",
	"Bean Bags",
	"Beauty & Personal Care",
	"Bed Pillows & Positioners",
	"Bed Risers",
	"Bed Safety Handles & Rails",
	"Bed Skirts",
	"Bedding",
	"Bedding Accessories",
	"Bedroom Aids & Accessories",
	"Bells & Sleigh Bells",
	"Belts",
	"Belts, Hoses & Pulleys",
	"Beverage Serveware",
	"Beverages",
	"Bible Study & Reference",
	"Billiard Balls",
	"Billiards & Pool",
	"Binoculars & Scopes",
	"Biographies & Memoirs",
	"Biological Sciences",
	"Birdcages",
	"Birds",
	"Blank Media",
	"Blankets & Swaddling",
	"Blankets & Throws",
	"Blasters & Foam Play",
	"Blinds & Shades",
	"Blu-ray",
	"Blue Light Blocking Glasses",
	"Board Games",
	"Boat Engine Parts",
	"Boat Fenders",
	"Boating",
	"Boating & Sailing",
	"Body",
	"Body & Trim",
	"Body Jewelry",
	"Body Washes",
	"Body Weight Scales",
	"Books",
	"Bottle-Feeding",
	"Bottled Beverages, Water & Drink Mixes",
	"Bottles",
	"Bowls",
	"Bowls & Dishes",
	"Boys",
	"Bracelets",
	"Braces, Splints & Supports",
	"Brackets",
	"Brad Nailers",
	"Brain Teasers",
	"Bras",
	"Bread & Loaf Pans",
	"Bubble Solution",
	"Bubbles",
	"Building Materials",
	"Building Sets",
	"Building Supplies",
	"Building Toys",
	"Bullet Cameras",
	"Bulletin Boards",
	"Bumper Stickers",
	"Bumper Stickers, Decals & Magnets",
	"Bun & Crown Shapers",
	"Bus Tubs",
	"Business Card Cases",
	"Buttons",
	"CB & Two-Way Radios",
	"CD-R",
	"CDs & Vinyl",
	"CPU Cooling Fans",
	"Cabinet & Drawer Organization",
	"Cables",
	"Cables & Accessories",
	"Cables & Adapters",
	"Cables & Interconnects",
	"Cake Toppers",
	"Calculators",
	"Calendars, Planners & Personal Organizers",
	"Camera & Photo",
	"Camp Kitchen",
	"Camping & Hiking",
	"Candle Making",
	"Candleholders",
	"Candles",
	"Candles & Holders",
	"Candlestick Holders",
	"Candy & Chocolate",
	"Candy & Chocolate Gifts",
	"Candy Making Supplies",
	"Candy Molds",
	"Canes",
	"Canes, Crutches & Accessories",
	"Canned, Jarred & Packaged Foods",
	"Caps & Hats",
	"Car Care",
	"Car Racks, Transportation & Storage",
	"Card & ID Cases",
	"Card Storage & Display",
	"Cards & Card Stock",
	"Carry-Ons",
	"Cars & Race Cars",
	"Carts & Stands",
	"Case Fans",
	"Cases",
	"Cases, Holsters & Sleeves",
	"Casseroles",
	"Cast & Wound Covers",
	"Casting Tools",
	"Casual",
	"Cat 6 Cables",
	"Cat Doors",
	"Cat Doors, Steps, Nets & Pens",
	"Catalytic Converters",
	"Catalytic Converters & Parts",
	"Catholicism",
	"Cats",
	"Ceiling Fans",
	"Ceiling Fans & Accessories",
	"Ceiling Lights",
	"Cell Phones & Accessories",
	"Cellular Shades",
	"Chains",
	"Chains & Sprockets",
	"Chairs & Seats",
	"Chalk",
	"Chandeliers",
	"Chargers & Power Adapters",
	"Charging Stations",
	"Charms",
	"Chemicals & Water Testing Products",
	"Cherries",
	"Chew Toys",
	"Children's Books",
	"Chokers",
	"Choppers",
	"Choppers & Mincers",
	"Christian Books & Bibles",
	"Christian Living",
	"Cigarette Lighters & Parts",
	"Civil Service",
	"Clamps",
	"Clarinet",
	"Classical",
	"Cleaning & Care",
	"Cleaning Equipment",
	"Cleaning Tools & Chemicals",
	"Cleansers",
	"Clipboards",
	"Clipboards & Forms Holders",
	"Clipper Combs & Guides",
	"Clips",
	"Clips & Barrettes",
	"Clips, Clamps & Rings",
	"Clocks",
	"Clothes Hangers",
	"Clothing",
	"Clothing & Closet Storage",
	"Clothing Accessories",
	"Clothing, Shoes & Jewelry",
	"Cloths",
	"Clutches",
	"Clutches & Evening Bags",
	"Coat Hangers",
	"Coats, Jackets & Vests",
	"Coaxial",
	"Coffee",
	"Coffee Mugs",
	"Coin & Button Cell",
	"Colanders",
	"Colanders & Food Strainers",
	"Cold Weather",
	"Collars",
	"Collars, Harnesses & Leashes",
	"Collectible Display & Storage",
	"Collectible Toys",
	"Coloring & Highlighting Tools",
	"Comedy",
	"Comforter Sets",
	"Comforters & Sets",
	"Commercial Paper Hand Towel Dispensers",
	"Compact Microwave Ovens",
	"Composting & Yard Waste Bins",
	"Composting Bins",
	"Compression Gauges",
	"Compressors",
	"Compressors & Parts",
	"Computer Accessories & Peripherals",
	"Computer Cable Adapters",
	"Computer Carts & Machine Stands",
	"Computer Components",
	"Computer Microphones",
	"Computers & Accessories",
	"Computers & Tablets",
	"Concealer",
	"Concertos",
	"Condiment Pots",
	"Connectors & Adapters",
	"Consoles",
	"Construction Paper",
	"Container Sets",
	"Control Arms",
	"Control Arms & Parts",
	"Controls",
	"Controls & Indicators",
	"Cookbooks, Food & Wine",
	"Cooking & Baking",
	"Cookware",
	"Cookware Sets",
	"Coolers",
	"Cosmetic Bags",
	"Cosmetic Display Cases",
	"Costumes",
	"Costumes & Accessories",
	"Costumes & Cosplay Apparel",
	"Country",
	"Cradles",
	"Craft & Sewing Supplies Storage",
	"Craft Supplies",
	"Crafting",
	"Crafts, Hobbies & Home",
	"Cranksets",
	"Creams & Moisturizers",
	"Cribs",
	"Cross-Country Skiing",
	"Cube Erasers",
	"Cuff",
	"Cuffs & Wraps",
	"Cups",
	"Cups & Mugs",
	"Cups, Mugs, & Saucers",
	"Curling Tongs",
	"Curtains & Drapes",
	"Cuticle Nippers",
	"Cuticle Tools",
	"Cutting Tools",
	"Cycling",
	"DVI",
	"DVI-HDMI Adapters",
	"Dartboards",
	"Darts & Equipment",
	"Data Storage",
	"Deadbolts",
	"Death & Grief",
	"Decals",
	"Decorations",
	"Decorative Accessories",
	"Decorative Balls",
	"Decorative Pillows, Inserts & Covers",
	"Decorative Signs & Plaques",
	"Deep Conditioners",
	"Dental Grills",
	"Desk Accessories & Workspace Organizers",
	"Desk Supplies Holders & Dispensers",
	"Desktop & Off-Surface Shelves",
	"Diagnostics & Screening",
	"Diapering",
	"Die-Cuts",
	"Die-Cutting & Embossing",
	"Diffusers",
	"Digital",
	"Digital Cameras",
	"Digital Scales",
	"Dimensional Measurement",
	"Dining & Entertaining",
	"Dinnerware",
	"Dinnerware & Serveware",
	"Disposable Diapers",
	"Disposable Food Storage",
	"Diving & Snorkeling",
	"Dock Lines & Rope",
	"Docking & Anchoring Equipment",
	"Dogs",
	"Dollhouse Accessories",
	"Dollhouses",
	"Dolls",
	"Dolls & Accessories",
	"Door & Stair Gates",
	"Door Hardware & Locks",
	"Door Knobs",
	"Doormats",
	"Doors",
	"Down Jackets & Parkas",
	"Downloadable Content",
	"Drama",
	"Drawer Organizers",
	"Drawing",
	"Drawing & Lettering Aids",
	"Drawing Media",
	"Dress Up & Pretend Play",
	"Dress-Up Accessories",
	"Dresses",
	"Drinkware",
	"Drive Train",
	"Drivetrain Components",
	"Drop & Dangle",
	"Dumbbells",
	"Dutch Ovens",
	"Décor",
	"EMF Meters",
	"Ear Care",
	"Earbud Headphones",
	"Early Childhood Education Materials",
	"Earrings",
	"Earth Sciences",
	"Edge & Corner Guards",
	"Education & Crafts",
	"Education & Reference",
	"Elastic",
	"Elastics & Ties",
	"Electric Lanterns",
	"Electric Shavers",
	"Electrical",
	"Electrical Device Mounts",
	"Electrical Testing",
	"Electronic Keyboards",
	"Electronic Learning Toys",
	"Electronics",
	"Electronics & Gadgets",
	"Emergency Strobe Lights",
	"Encyclopedias & Subject Guides",
	"Engine Cooling & Climate Control",
	"Engine Tools",
	"Erasers",
	"Erasers & Correction Products",
	"Ethernet Cables",
	"Event & Party Supplies",
	"Everyday Bras",
	"Examination Supplies & Consumables",
	"Exercise & Fitness",
	"Exercise Machine Attachments",
	"Exercise Machine Parts & Accessories",
	"Exhaust & Emissions",
	"Exhaust Systems & Parts",
	"Exterior",
	"Exterior Accessories",
	"Exterior Mirrors",
	"Eyeliner",
	"Eyes",
	"Eyeshadow",
	"Face",
	"Face Mists",
	"Fan Shop",
	"Fans & Cooling",
	"Fashion Sneakers",
	"Fasteners",
	"Faucet Parts",
	"Faucet Washers",
	"Fedoras",
	"Feeders",
	"Feeding",
	"Feeding & Watering Supplies",
	"Feeding Mats",
	"Filter Accessories",
	"Filters",
	"Fire Pits",
	"Fire Pits & Outdoor Fireplaces",
	"Fish & Aquatic Pets",
	"Fishing",
	"Fitted Sheets",
	"Fixed Showerheads",
	"Flags",
	"Flashlights",
	"Flatware",
	"Flatware Sets",
	"Flip Cases",
	"Floor Cleaners",
	"Floor Mats",
	"Floor Mats & Cargo Liners",
	"Flours & Meals",
	"Flowmeters",
	"Fly Fishing",
	"Fly Tying Equipment",
	"Foam Ammunition",
	"Foam Blaster Sets",
	"Food & Dish Transport",
	"Food Containers",
	"Food Service Equipment & Supplies",
	"Food Storage",
	"Food Storage Bags",
	"Foot & Hand Care",
	"Foot Health",
	"Foot, Hand & Nail Care",
	"Footwear",
	"Forms & Genres",
	"Forms, Recordkeeping & Money Handling",
	"Fracture & Cast Boots",
	"Frames",
	"Frosting, Icing & Decorations",
	"Fruits",
	"Fuel Filters",
	"Furniture",
	"GPS, Finders & Accessories",
	"Galvanic Machines",
	"Game & Recreation Room Furniture",
	"Games",
	"Games & Accessories",
	"Gaming Keyboards",
	"Gaming Mice",
	"Garage Doors, Openers & Parts",
	"Garden Sculptures & Statues",
	"Gardening & Lawn Care",
	"Garlands",
	"Garment Steamers",
	"Gates & Gate Extensions",
	"Gauges",
	"Gavels",
	"Gel Ink Rollerball Pens",
	"Genre for Featured Categories",
	"Geography & Cultures",
	"Ghee",
	"Gift Bags",
	"Gift Wrapping Supplies",
	"Girls",
	"Glass Care",
	"Glassware & Drinkware",
	"Glitter",
	"Glitters",
	"Gloves & Mittens",
	"Golf",
	"Golf Course GPS Units",
	"Graphics Cards",
	"Graphing",
	"Green",
	"Greeting Cards",
	"Grocery & Gourmet Food",
	"Grooming",
	"Growing Up & Facts of Life",
	"Guitar & Bass Accessories",
	"Gymnastics",
	"HEPA Air Purifiers",
	"HVAC",
	"Hair Accessories",
	"Hair Brushes",
	"Hair Care",
	"Hair Clippers & Accessories",
	"Hair Coloring Products",
	"Hair Cutting Tools",
	"Hair Extensions",
	"Hair Extensions, Wigs & Accessories",
	"Hair Sprays",
	"Halogen Bulbs",
	"Hand & Foot Warmers",
	"Hand Creams & Lotions",
	"Hand Tools",
	"Hand Warmers",
	"Handbags & Wallets",
	"Handheld Flashlights",
	"Handheld Games",
	"Handlebar Risers",
	"Handlebars & Components",
	"Hands Free Flashlights & Headlamps",
	"Hanging Baskets",
	"Hanging Organizers",
	"Hanging Ornaments",
	"Hanging Planters",
	"Hardcover Executive Notebooks",
	"Hardware",
	"Harnesses",
	"Hats & Caps",
	"Head Covers",
	"Headbands",
	"Headcollars",
	"Headlamps",
	"Headlight Assemblies",
	"Headlight Assemblies, Parts & Accessories",
	"Headphones & Earbuds",
	"Headphones, Earbuds & Accessories",
	"Headsets",
	"Headsets & Microphones",
	"Headwear",
	"Health & Household",
	"Health Care",
	"Health Monitors",
	"Health, Fitness & Dieting",
	"Heater",
	"Heater Blend Door Levers",
	"Heaters & Accessories",
	"Heating, Cooling & Air Quality",
	"Heel Cushions & Cups",
	"Hex Keys",
	"Hinges",
	"Historical Fiction",
	"History",
	"History & Criticism",
	"Home & Kitchen",
	"Home Audio",
	"Home Audio Accessories",
	"Home Bar Furniture",
	"Home Décor Accents",
	"Home Décor Products",
	"Home Fragrance",
	"Home Improvement & Design",
	"Hooks",
	"Hose Connectors & Accessories",
	"Hoses",
	"Hot & Cold Therapies",
	"Hot Water Bottles",
	"Household Batteries",
	"Household Cleaning",
	"Household Supplies",
	"Humor",
	"Humor & Entertainment",
	"Hunting & Fishing",
	"Hydration & Filtration",
	"Ice Buckets",
	"Ice Buckets & Tongs",
	"Ice Cream Scoops",
	"Ice Hockey",
	"Identification Badges & Supplies",
	"Incandescent Bulbs",
	"Incense & Incense Holders",
	"Incense Holders",
	"Independently Distributed",
	"Indoor Bike Storage",
	"Indoor String Lights",
	"Industrial & Scientific",
	"Industrial Electrical",
	"Industrial Hardware",
	"Industrial Switches",
	"Infant & Toddler Beds",
	"Inkjet Ink Cartridges",
	"Inserts & Insoles",
	"Instant Cameras",
	"Instrument Accessories",
	"Insulated Beverage Containers",
	"Interior",
	"Interior Accessories",
	"Internal Components",
	"International Music",
	"Invitations",
	"Irons",
	"Irons & Steamers",
	"Jacks & Stabilizers",
	"Janitorial & Sanitation Supplies",
	"Jar Candles",
	"Jeans",
	"Jewelry",
	"Jewelry Accessories",
	"Jewelry Boxes",
	"Jewelry Boxes & Organizers",
	"Jewelry Casting Supplies",
	"Jewelry Clasps",
	"Jewelry Findings",
	"Jewelry Sets",
	"Jewelry Trays",
	"Juices",
	"Jump Starters, Battery Chargers & Portable Power",
	"Key Shells",
	"Keyboards",
	"Keyboards & MIDI",
	"Keyboards, Mice & Accessories",
	"Keyless Entry Systems",
	"Keypads & Remotes",
	"Keyrings, Keychains & Charms",
	"Kids & Baby",
	"Kids' Backpacks",
	"Kids' Bedding",
	"Kids' Furniture",
	"Kids' Tricycles",
	"Kitchen & Bath Fixtures",
	"Kitchen & Dining",
	"Kitchen & Table Linens",
	"Kitchen Playsets",
	"Kitchen Storage & Organization Accessories",
	"Kitchen Toys",
	"Kitchen Utensils & Gadgets",
	"Knee Braces",
	"LED Bulbs",
	"LED Strip Lights",
	"Label Printers",
	"Labels, Indexes & Stamps",
	"Landscape Lighting",
	"Lanterns",
	"Lap Desks",
	"Laptop Accessories",
	"Laptops",
	"Lard & Shortening",
	"Laser Rangefinders",
	"Laundry Bags",
	"Laundry Baskets",
	"Laundry Storage & Organization",
	"Leaders & Notable People",
	"Learning & Education",
	"Leashes",
	"Leg & Foot Supports",
	"Leg Warmers",
	"Legacy Systems",
	"Leisure Sports & Game Room",
	"Leveling & Stablilization",
	"License Plate Covers & Frames",
	"Lifejackets",
	"Light Bulbs",
	"Lighting",
	"Lighting & Ceiling Fans",
	"Lighting & Electrical",
	"Lighting & Studio",
	"Lighting Assemblies & Accessories",
	"Lighting Controls & Modifiers",
	"Lights & Lanterns",
	"Lights & Lighting Accessories",
	"Lingerie",
	"Lingerie, Sleep & Lounge",
	"Lips",
	"Lipstick",
	"Literature & Fiction",
	"Litter & Housebreaking",
	"Litter Boxes",
	"Live Sound & Stage",
	"Loaf Pans",
	"Lug Nuts",
	"Lug Nuts & Accessories",
	"Luggage",
	"Luggage & Travel Gear",
	"Luggage Tags",
	"Luggage Tags & Handle Wraps",
	"Lunch Bags",
	"MP3 & MP4 Players",
	"Magazine Holders",
	"Magnifiers",
	"Maintenance, Upkeep & Repairs",
	"Makeup",
	"Makeup Mirrors",
	"Marker Light Assemblies",
	"Mascara",
	"Masks",
	"Masks & Respirators",
	"Massage Balls",
	"Massage Tools",
	"Massage Tools & Equipment",
	"Material Handling Products",
	"Material Transport Equipment",
	"Measuring Tools & Scales",
	"Medical Books",
	"Medical Supplies & Equipment",
	"Medication Aids",
	"Medicine",
	"Medicine & Health Sciences",
	"Memo Holders",
	"Memory",
	"Men",
	"Men's",
	"Metals & Alloys",
	"Microdermabrasion Devices",
	"Microphone Cables",
	"Microscopes",
	"Microwave Ovens",
	"Milling Machines",
	"Mirrors",
	"Mirrors & Parts",
	"Mobility & Daily Living Aids",
	"Mobility Aids & Equipment",
	"Model & Hobby Building",
	"Moisturizers",
	"Molds",
	"Money Handling Products",
	"Monitor Accessories",
	"Monitor Arms",
	"Motorcycle & Powersports",
	"Mouse Pads",
	"Mouse Pads & Wrist Rests",
	"Movies",
	"Movies & TV",
	"Mufflers",
	"Mug Sets",
	"Music",
	"Musical Instruments",
	"Nail Art & Polish",
	"Nail Art Accessories",
	"Nailers",
	"Nailers & Staplers",
	"Napkins",
	"Native American",
	"Neck & Cervical Pillows",
	"Necklaces",
	"Nets",
	"Nets & Accessories",
	"New, Used & Rental Textbooks",
	"Night Lights",
	"Nightgowns & Sleepshirts",
	"Nintendo DS",
	"Nintendo NES",
	"Nintendo Systems",
	"North America",
	"Notebooks & Writing Pads",
	"Novelty",
	"Novelty & Gag Toys",
	"Novelty & More",
	"Novelty Lighting",
	"Nursery",
	"Nut & Bolt Assortment Sets",
	"OTC Medications & Treatments",
	"Occupational Health & Safety Products",
	"Office & School Supplies",
	"Office Electronics",
	"Office Furniture & Lighting",
	"Office Products",
	"Oils",
	"On-Camera Video Lights",
	"Open Storage Bins",
	"Optics",
	"Orchestral Strings Accessories & Parts",
	"Organization, Storage & Transport",
	"Ornaments",
	"Orthodontic Supplies",
	"Other Sports",
	"Outdoor Décor",
	"Outdoor Heating & Cooling",
	"Outdoor Lighting",
	"Outdoor Recreation",
	"Outdoor Speakers",
	"Outdoor Statues",
	"Outlets & Accessories",
	"Ovens & Toasters",
	"Over-Ear Headphones",
	"PC",
	"Pacifiers",
	"Pacifiers, Teethers & Teething Relief",
	"Packing Organizers",
	"Pain Relievers",
	"Paint Application Tools",
	"Paint Edgers",
	"Paint Pens, Markers & Daubers",
	"Paint, Wall Treatments & Supplies",
	"Paint-By-Number Kits",
	"Painting",
	"Painting Supplies & Tools",
	"Painting Tools",
	"Painting, Drawing & Art Supplies",
	"Panels",
	"Pantry Staples",
	"Paper",
	"Paper & Paper Crafts",
	"Paper & Plastic",
	"Paper Ribbon & Raffia",
	"Paraffin Baths",
	"Parts",
	"Parts & Accessories",
	"Parts & Components",
	"Parts & Connectors",
	"Party Supplies",
	"Patio Furniture & Accessories",
	"Patio, Lawn & Garden",
	"Pegboard Hooks",
	"Pencil Holders",
	"Pendant Lights",
	"Pendant Necklaces",
	"Pendants & Coins",
	"Pens",
	"Pens & Markers",
	"Pens & Refills",
	"Performance Parts & Accessories",
	"Performing Arts",
	"Personal Care",
	"Personal Protective Equipment",
	"Pet Supplies",
	"Pets & Animal Care",
	"Photo Studio",
	"Piercing & Tattoo Supplies",
	"Piercing Jewelry",
	"Pill Organizers",
	"Pillowcases",
	"Pipe Clamps",
	"Pipe Fittings",
	"Pipes, Pipe Fittings & Accessories",
	"Pitching Trainers",
	"Place Mats",
	"Planners",
	"Planners, Refills & Covers",
	"Plantar Fasciitis Braces",
	"Plastic Plants",
	"Platforms, Stands & Shelves",
	"Platters",
	"PlayStation 2",
	"PlayStation 4",
	"PlayStation Systems",
	"Playards",
	"Point & Shoot Digital Cameras",
	"Politics & Social Sciences",
	"Pool & Spa Replacement Parts",
	"Pool Balancers",
	"Pool Clarifiers & Enzymes",
	"Pools & Water Toys",
	"Pools, Hot Tubs & Supplies",
	"Pop",
	"Porch & Patio Lights",
	"Portable & Arranger Keyboards",
	"Portable Audio & Video",
	"Posing Props",
	"Posters & Prints",
	"Pots & Pans",
	"Pots, Planters & Container Accessories",
	"Power & Hand Tools",
	"Power Accessories",
	"Power Converters",
	"Power Cords",
	"Power Finishing Tool Parts & Accessories",
	"Power Sander Parts & Accessories",
	"Power Tool Parts & Accessories",
	"Power Tools",
	"Power Water Pumps",
	"Pre-Cut Adjustable Elastics",
	"Presentation Boards",
	"Printer Ink & Toner",
	"Printer Parts & Accessories",
	"Printers",
	"Printers & Accessories",
	"Professional Dental Supplies",
	"Professional Medical Supplies",
	"Projection Screens",
	"Projector Accessories",
	"Propane Space Heaters",
	"Pushbutton Switches",
	"Puzzles",
	"RV Parts & Accessories",
	"Racks & Holders",
	"Racks, Shelves & Drawers",
	"Racquets",
	"Radios",
	"Range Hoods",
	"Ranges, Ovens & Cooktops",
	"Rash Guards",
	"Raw Materials",
	"Reading Glasses",
	"Receiving Blankets",
	"Reeds",
	"Reference",
	"Refillable Containers",
	"Relationships",
	"Remote & App Controlled Vehicle Parts",
	"Remote & App Controlled Vehicles",
	"Remote & App Controlled Vehicles & Parts",
	"Remote Controls",
	"Replacement Parts",
	"Replacement Sunglass Lenses",
	"Reservoirs",
	"Respirator Parts",
	"Restroom Fixtures",
	"Reusable Grocery Bags",
	"Ribbons",
	"Rice Cookers",
	"Rings",
	"Robe & Towel Hooks",
	"Rod & Reel Combos",
	"Rollerball Pens",
	"Rolling Pins",
	"Rough Plumbing",
	"Rug Pads",
	"Rugs, Pads & Protectors",
	"Safety",
	"Safety & Flotation Devices",
	"Safety & Security",
	"Safety & Survival",
	"Safety Products",
	"Safety Signs & Signals",
	"Safety Warning Tapes",
	"Salad Bowls",
	"Salon & Spa Equipment",
	"Scales",
	"Science & Math",
	"Science Kits & Toys",
	"Scientific",
	"Scrapbooking & Stamping",
	"Screen Protectors",
	"Screens",
	"Screwdriver Sets",
	"Screwdrivers & Nut Drivers",
	"Screws",
	"Sculptures",
	"Seasonal Décor",
	"Seasonal Lighting",
	"Seasoning & Spice Tools",
	"Security & Surveillance",
	"Security Lock Boxes",
	"Self-Help",
	"Serveware",
	"Serving Bowls & Tureens",
	"Serving Dishes, Trays & Platters",
	"Serving Trays",
	"Sewing",
	"Sewing Notions & Supplies",
	"Shampoo & Conditioner",
	"Shampoo & Conditioner Sets",
	"Shave & Hair Removal",
	"Sheet & Pillowcase Sets",
	"Sheets & Pillowcases",
	"Shelf Brackets & Supports",
	"Shelf Dividers",
	"Shelf Liners & Dividers",
	"Shim Stock",
	"Shims & Shim Stock",
	"Shirts",
	"Shocks, Struts & Suspension",
	"Shoe & Boot Trees",
	"Shoe Care & Accessories",
	"Shoe Decoration Charms",
	"Shoe, Jewelry & Watch Accessories",
	"Shoes",
	"Shooting",
	"Short Stories & Anthologies",
	"Shortwave Radios",
	"Shoulder & Chin Rests",
	"Shower & Bath Supplies",
	"Shower Curtain Sets",
	"Shower Curtains",
	"Shower Curtains, Hooks & Liners",
	"Shower Installation Kits",
	"Showerheads",
	"Showers & Shower Parts",
	"Side Combs",
	"Side Marker & Turn Signal Combos",
	"Signal Light Assemblies",
	"Signs",
	"Single Board Computers",
	"Single Rods",
	"Single-Serve Capsules & Pods",
	"Skate Accessories",
	"Skiing",
	"Skillets",
	"Skin Care",
	"Skin Care Tools",
	"Skis",
	"Skullies & Beanies",
	"Sleep & Lounge",
	"Sleep Soothers",
	"Sleeves",
	"Slime & Putty Toys",
	"Slippers",
	"Small Appliances",
	"Smartwatch Accessories",
	"Smartwatch Bands",
	"Smartwatch Cases",
	"Snacks & Sweets",
	"Snow Globes",
	"Soaps",
	"Soccer",
	"Social Sciences",
	"Socket & Socket Wrench Sets",
	"Socket Head Screws",
	"Sockets & Socket Sets",
	"Soft Drinks",
	"Solid Feeding",
	"Sony Pictures Home Entertainment",
	"Space Heaters",
	"Spade",
	"Sparkling Juice",
	"Speakers",
	"Special Diet",
	"Specialty Appliances",
	"Specialty Tools & Gadgets",
	"Speedometers",
	"Sports",
	"Sports & Handheld GPS",
	"Sports & Outdoor Play",
	"Sports & Outdoor Recreation Accessories",
	"Sports & Outdoors",
	"Sports Water Bottles",
	"Spotlights",
	"Springs",
	"Squeak Toys",
	"Stacking Blocks",
	"Stage & Studio Cables",
	"Stained Glass Making",
	"Stainless Steel",
	"Stamps",
	"Stamps & Stamp Supplies",
	"Standard",
	"Standard Litter Boxes",
	"Standard Outlets",
	"Stationery & Gift Wrapping Supplies",
	"Statues",
	"Steering Accessories",
	"Steering Wheels",
	"Steering Wheels & Accessories",
	"Step Lights",
	"Stethoscopes",
	"Stick Umbrellas",
	"Stickers",
	"Storage & Organization",
	"Storage & Transport",
	"Store Signs",
	"Store Signs & Displays",
	"Strand",
	"Strength Training Equipment",
	"Stretch",
	"Strippers",
	"Strobe & Safety Lights",
	"Strollers",
	"Strollers & Accessories",
	"Stud",
	"Studio Specials",
	"Stuffed Animals & Plush Toys",
	"Stuffed Animals & Teddy Bears",
	"Styling Products",
	"Styling Tools & Appliances",
	"Subject Notebooks",
	"Substance Analysis Instrumentation",
	"Suggestion Boxes",
	"Sun Hats",
	"Sunglasses",
	"Sunglasses & Eyewear Accessories",
	"Surveillance Camera Cables",
	"Surveillance Cameras",
	"Swaddling Blankets",
	"Sweaters",
	"Switches & Dimmers",
	"Swivels & Snaps",
	"T-Shirts",
	"TIG Welding Equipment",
	"TV",
	"Tablecloths",
	"Tablet Accessories",
	"Tableware",
	"Tactical & Personal Defense",
	"Tactical Backpacks",
	"Tactical Bags & Packs",
	"Tape, Adhesives & Fasteners",
	"Tapestries",
	"Tattoo Kits",
	"Tattoo Supplies",
	"Tea",
	"Tea Kettles",
	"Team Sports",
	"Teen & Young Adult",
	"Teethers",
	"Television & Video",
	"Temporary Tattoos",
	"Tennis",
	"Tennis & Racquet Sports",
	"Terminal Tackle & Accessories",
	"Terminals",
	"Test, Measure & Inspect",
	"Thermocoolers",
	"Thermometers & Timers",
	"Thermoses",
	"Thread",
	"Throw Pillow Covers",
	"Throws",
	"Tie Sets",
	"Ties, Cummerbunds & Pocket Squares",
	"Tiles",
	"Timer Switches",
	"Timers",
	"Tire & Wheel Sets",
	"Tire & Wheel Tools",
	"Tire Repair Tools",
	"Tires & Wheels",
	"Toaster Ovens",
	"Today's Country",
	"Toiletry Bags",
	"Toner Cartridges",
	"Tool Boxes",
	"Tool Holsters",
	"Tool Organizers",
	"Tools",
	"Tools & Accessories",
	"Tools & Equipment",
	"Tools & Home Improvement",
	"Totes",
	"Touch On Faucets",
	"Towel Sets",
	"Towels",
	"Towing Products & Winches",
	"Toy Figures & Playsets",
	"Toys",
	"Toys & Games",
	"Traditional Laptops",
	"Trailer Accessories",
	"Training Equipment",
	"Travel & To-Go Food Containers",
	"Travel Accessories",
	"Travel Cases",
	"Travel Duffels",
	"Treatments & Masks",
	"Tree Skirts",
	"Tricycles, Scooters & Wagons",
	"Trim",
	"Trim & Embellishments",
	"Trucks",
	"Tumblers & Water Glasses",
	"USB Cables",
	"USB Flash Drives",
	"USB Microscopes",
	"Umbrellas",
	"Umbrellas & Shade",
	"Uniforms, Work & Safety",
	"Utensils",
	"Utility Carts",
	"Vacuum Parts & Accessories",
	"Vacuum Sealer Bags",
	"Vacuums & Floor Care",
	"Vases",
	"Vehicles",
	"Vest Harnesses",
	"Video Games",
	"Video Surveillance",
	"Violin",
	"Virtual Reality (VR) Headsets",
	"Vision",
	"Visual Impairment Aids",
	"Waist Packs",
	"Wall Art",
	"Wall Clocks",
	"Wall Controls",
	"Wall Lights",
	"Wall Stickers & Murals",
	"Wall Switches",
	"Wall-Mounted Mirrors",
	"Wallets",
	"Wallets, Card Cases & Money Organizers",
	"Wallpaper",
	"Wallpaper & Wallpapering Supplies",
	"Warner Home Video",
	"Warning & Emergency Lights",
	"Watches",
	"Water",
	"Water Filters",
	"Water Pumps, Parts & Accessories",
	"Water Sports",
	"Watering Equipment",
	"Webcams",
	"Webcams & VoIP Equipment",
	"Weight Belts",
	"Weighted Blankets",
	"Weights & Accessories",
	"Welding & Soldering",
	"Welding Equipment",
	"Welding Equipment & Accessories",
	"Welding Systems",
	"Wellness & Relaxation",
	"Wheat Flours & Meals",
	"Wheels & Tires",
	"Wigs",
	"Winches",
	"Wind & Woodwind Accessories",
	"Window Rods",
	"Window Stickers",
	"Window Stickers & Films",
	"Window Treatment Hardware",
	"Window Treatments",
	"Wine & Champagne Glasses",
	"Wine Decanters",
	"Wine Glasses",
	"Winter Sports",
	"Wire Strippers",
	"Wiring & Connecting",
	"Women",
	"Women's Health",
	"Workholding Devices",
	"Wreaths",
	"Wrenches",
	"Wrist Watches",
	"Writing & Correction Supplies",
	"Xbox 360",
	"Xbox One",
	"Xbox Systems",
	"Yard Signs",
	"Yarn Storage",
	"Yoga",
	"Zippers",
	"pet food ASINs"
]